server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
       defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: quick-eureka