spring:
  application:
    name: quick-buy-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quickbuy?characterEncoding=utf8
    username: root
    password: 123
server:
  port: 8881
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka